### ISSUE TITLE
Results seems empty?

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [arpcard/rgi#5]
Hello,
I am having trouble regarding results of rgi, final files obtained are empty and non filtered result are present in a .temp.blastRes.xml file.
Happens even when mapping flat Card homology fasta file to Card.json. 
Seems to be related to diamond usage, as using the default blast gives output.
Any suggestion?

**Comment by arpcard** [comment]
Can you share the command you ran? Input file too if you can?

**Comment by Sebastien-Raguideau** [comment]
The exact command is the following : 
sudo rgi main --input_sequence ~/seb/Database/CARD/protein_fasta_protein_homolog_model.fasta --output_file Results_rgi --input_type protein -a DIAMOND
I need a sudo since the folder of installation is owned by root, and rgi need permission to write log at that place.  Input file is from the Card database and was intended as a test, also because it is small and won't take too long.
Taking out the -a diamond make it works, but I'd rather not wait for blast.

**Comment by arpcard** [comment]
> I need a sudo since the folder of installation is owned by root, and rgi need permission to write log at that place.

You can use `--local` flag to install database locally then you don't have to use `sudo`. Also, once the database is created for system wide run you don't need to use `sudo`. 

> Taking out the -a diamond make it works, but I'd rather not wait for blast.

We have updated the default threads used from 4 to 32, this should speed up diamond or blast.

**Comment by arpcard** [comment]
@Sebastien-Raguideau install from latest commit (https://github.com/arpcard/rgi/archive/master.zip), before release.

**Comment by Sebastien-Raguideau** [comment]
You realise that increasing the number of thread for blast does not allow to use diamond? Can you consider the issue to be solved?

**Comment by arpcard** [comment]
What do you mean by `number of thread for blast does not allow to use diamond`? The options are as follows:
```
  -a ALIGNER, --alignment_tool ALIGNER
                        specify alignment tool. Options are BLAST or DIAMOND
                        (default = BLAST)
  -n THREADS, --num_threads THREADS
                        number of threads (CPUs) to use in the BLAST search
                        (default=32)
```
The file `protein_fasta_protein_homolog_model.fasta` is big it's going to take a while when using 4 threads to align the sequences.

**Comment by Sebastien-Raguideau** [comment]
From your previous answer, I  had the feeling that you only changed the default number of thread for aligners. Which should not per se resolve my issue with diamond. Issue beeing, not getting any result when adding option -a DIAMOND. Maybe this is resolved with the last commit. 
I will try. 
Thanks.

**Comment by arpcard** [comment]
The `--num_threads` is used by both diamond and blast. Let us know if commit
625aeae doesn't resolve the issue, Cheers.
